service: serverless-pixels

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-appsync-plugin

custom:
  accountId: ACCOUNT_ID
  dynamodb:
    start:
      port: 8000
      inMemory: false
      migrate: true
      seed: true
  appSync:
    authenticationType: API_KEY
    mappingTemplates:
      - dataSource: Pixels
        type: Query
        field: getPixels
        request: "getPixels-request.txt"
        response: "getPixels-response.txt"
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Pixels
        description: 'Pixels table'
        config:
          tableName: 'Pixels'
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Dynamo-${self:custom.appSync.serviceRole}"

resources:
  Resources:
    PixelsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        KeySchema:
          -
            AttributeName: pixel_id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: pixel_id
            AttributeType: S
          -
            AttributeName: program_id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: "Pixels"
        GlobalSecondaryIndexes:
          -
            IndexName: program-pixels
            KeySchema:
              -
                AttributeName: program_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    AppSyncServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
          RoleName: "Dynamo-AppSyncServiceRole"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Principal:
                  Service:
                    - "appsync.amazonaws.com"
                Action:
                  - "sts:AssumeRole"
          Policies:
            -
              PolicyName: "Dynamo-AppSyncServiceRole-Policy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action:
                      - "dynamodb:Query"
                      - "dynamodb:BatchWriteItem"
                      - "dynamodb:GetItem"
                      - "dynamodb:DeleteItem"
                      - "dynamodb:PutItem"
                      - "dynamodb:Scan"
                      - "dynamodb:UpdateItem"
                    Resource:
                      - "arn:aws:dynamodb:us-east-1:*:table/Pixels"
                      - "arn:aws:dynamodb:us-east-1:*:table/Pixels/*"